# Parameters for data and model piplines

# Data paths
data:
  raw_path: "data/raw"
  processed_path: "data/processed"

# Preprocessing configuration
preprocessing:
  transforms:
    # Image resizing
    resize:
      height: 224
      width: 224
    
    # Normalization (ImageNet values - adjust when using other models)
    normalize: # For grayscale images only
      mean: [0.5] 
      std: [0.5]  
      
    
    # Data augmentation (only applied to training set)
    augmentation:
      enabled: true 
      random_horizontal_flip: true

# MLflow configuration
mlflow:
  experiment_name: "breast_cancer_classification"
  tracking_uri: "https://dagshub.com/DannyLCG/breastCancerBinClass.mlflow"

# Model configuration
model:
  name: "efficientnet_b0" 
  pretrained: true
  num_classes: 2

# Training configuration 
training:
  batch_size: 32 # Adjust based on GPU memory
  learning_rate: 0.001 
  weight_decay: 0.01
  dropout: 0.2
  epochs: 100
  patience: 10
  optimizer: "adamw" # OR ""
  
# DVC configuration
dvc:
  remote:
    name: "myremote"
    # url: "s3://my-bucket/data"  # Update with DVC S3 bucket
